### ISSUE TITLE
Unable to link twitch account

### ISSUE THREAD

**Issue by jsand5048** [TwitchedApp/Twitched#16] opened 2018-04-02 15:06 UTC
### Description
Once you enter the code the twitched app on roku never continues and does not successfully link account.

### Steps to Reproduce
1. Click Followed and be prompted for code
2. Enter code, receive pop up stating that the account is linked
3. Does not proceed past this, if you back out it does not link your account

...

**Expected behavior:** Twitch account should be linked

**Actual behavior:** Not linked

**Roku Model:** Tried on roku streaming stick, roku premiere and roku 3.

**Roku Firmware Version:** newest version

**Twitched Version:** newest version

### Additional Information
[Any other information related to the problem]

**Comment by Tibbetts24** [comment] 2018-04-02 17:53
Have this issue as well.

**Comment by rolandoislas** [comment] 2018-04-02 20:30
On which version does this occur, Twitched or Twitched Zero? The version number would be helpful as there are also beta builds of both.

**Comment by Tibbetts24** [comment] 2018-04-02 21:13
For me it is the Twitched 1.4 Beta.

**Comment by rolandoislas** [comment] 2018-04-02 21:21
@Tibbetts24 the beta app cannot be linked to a Twitch account directly since it is not using Twitched's production servers. It will, however, share the authentication details from one of the released versions.

**Comment by Tibbetts24** [comment] 2018-04-02 22:17
Oh ok. Thank you.

**Comment by jsand5048** [comment] 2018-04-03 03:47
This is occurring on Twitched (the 99c paid version) I'm not sure the version number as I'm currently not home but I will reply with it. I'm assuming its a non beta version as i downloaded this app directly from the roku channel store.

**Comment by jsand5048** [comment] 2018-04-03 13:51
I have version 1.3 build 1908

**Comment by rolandoislas** [comment] 2018-04-04 01:04
@jsand5048 Unfortunately, I am unable to reproduce this error. What does the _Followed_ tab display after the post-link dialog?

**Comment by jsand5048** [comment] 2018-04-04 02:03
It says the account is linked and does not go away. I will try again later, I actually think it may have been a twitch issue as I wasn't able to log into the twitch app using my Xbox either.

**Comment by jsand5048** [comment] 2018-04-08 20:50
Hi I tried again and it's working. It looks like it was a twitch issue.

**Comment by seanbperiod** [comment] 2018-04-08 21:33
I have this issue too. 1.3 on Roku, and linked the account 5 times, and it won't take.

**Comment by rolandoislas** [comment] 2018-04-09 01:53
I am closing this issue for now as I cannot reproduce the error and it does not seem to be persistent.

For anyone else having the issue, be sure to remain on the link screen after linking. It will close itself.

**Comment by rolandoislas** [comment] 2018-04-10 04:31
A database issue is being investigated.

**Closed** 2018-04-15 03:41 UTC
Labels: bug, fix applied, resolved
