### ISSUE TITLE
Low res covers/thumbnails (fhd UI support)

### ISSUE THREAD

**Issue by jbaconbits** [TwitchedApp/Twitched#18] opened 2018-05-12 17:30 UTC
Just wondering, is the UI only set to hd? Elements look awfully blurry, especially on a 4K tv. 

If so, it would be nice if fhd UI support was added since many of the current roku models now support 1080p UIs.

**Comment by rolandoislas** [comment] 2018-05-15 00:48
![](https://github.trello.services/images/mini-trello-icon.png) [FHD UI](https://trello.com/c/3h56BfCV/51-fhd-ui)

**Comment by rolandoislas** [comment] 2018-05-21 23:18
FHD UI support has been added to the v1.5 beta: https://my.roku.com/add/Q2M6C6.

**Comment by jbaconbits** [comment] 2018-05-21 23:34
Looks much better!

I noticed there seems to be some pixels missing on the upper left of the selection box overlaying the main menu items on the home screen. 

Also, there’s also some formatting issues with chat where emojis are on top of the text.  Not sure these are related to the UI update though.

**Comment by rolandoislas** [comment] 2018-05-27 05:47
The list selection background has been fixed in the latest build. 

As for the emotes in chat, some improvements have been made, but the issue is with the calculated text size returning different values than the size that actually appears in text labels.

**Comment by jbaconbits** [comment] 2018-05-27 16:59
Another small bug: The info overlay when you press “ok” during video playback isn’t centered at the bottom like it normally is, and instead floats in the middle of the screen and to the left.

**Comment by rolandoislas** [comment] 2018-06-03 17:17
The stream title overlay is fixed in the latest build.

**Closed** 2018-06-09 20:12 UTC
Labels: enhancement, resolved
