### ISSUE TITLE
Non-English streams throwing error code: 3003

### ISSUE THREAD

**Issue by tlukechess** [TwitchedApp/Twitched#34] opened 2018-08-10 12:22 UTC
I've noticed that this error is only thrown when the streamers language choice is anything but EN (English).
This was realized when a favorite Australian (an English speaking country) streamer of mine went to South Korea (non-English speaking country) for a week to practice a game before a major event here in the United States.  

Upon arriving in South Korea, he changed his Twitch language setting to KO (Korean) for whatever reason, and his stream stopped working for me on Roku-Twitched.  Upon returning to Australia after the event here in the US, he forgot to change his Twitch language setting back to English -- (edit #1a) still can't watch his stream.  

(Edit #1b)
Was hoping my infinite failed attempts and continuously receiving the error code would be logged somewhere and the developer(s) would have noticed and corrected this issue by now.   
 
How to reproduce:
1. Turn on Roku
2. Open Twitched App
3. Find any non-English streamer (localization set to anything but EN)
4. Hit play and be sad

(Edit #2)
Roku Model - Roku 3
Roku Firmware - After Twitch ended support for the PS3 a few weeks ago, I bought the Roku for the sole purpose of being able to watch streams on Twitch(ed) on my TV.  When that didn't work, I returned the Roku and got a ps4 instead.  Don't know/remember the firmware version unfortunately.
Twitched Version - see above.

**Comment by rolandoislas** [comment] 2018-08-10 21:42
I am unable to reproduce this error.

**Comment by moonlit** [comment] 2018-08-16 10:36
Received this error on both official live StarCraft streams tonight (the stream with English commentary is also marked as "Language: ko"). Issue corrected by enabling Korean language in Settings. Roku Express+ (3910)

**Comment by JoshIce** [comment] 2018-08-18 13:44
I'm having this issue as well. I've reinstalled and logged in and out of the app to no avail.
Roku Model - Roku 3 4230X
Software version - 8.1.0 build 4145-04
The streamer I'm trying to watch is ThijsHS, who has his language set to NL on Twitch.
This is also seems to be a recent issue, as I've been able to watch this streamer in the past.

**Comment by rolandoislas** [comment] 2018-08-19 06:16
A fix has been applied to the latest [staging version](https://my.roku.com/add/DPQCZJ).

**Comment by JoshIce** [comment] 2018-08-20 11:49
The issue is fixed for me. Hopefully @tlukechess can confirm the fix worked.

**Closed** 2018-11-15 11:59 UTC
Labels: bug, fix applied
